version: '3.3'
services:
    minecraft-server:
        ports:
            - '25565:25565'
        environment:
            - EULA=TRUE
            - ONLINE_MODE=FALSE
            - SEED="yunusleyla"
            - LEVEL=manivela
            - LEVEL_TYPE=AMPLIFIED
            - VIEW_DISTANCE=20
            - SNOOPER_ENABLED=false
            - ENABLE_ROLLING_LOGS=true
            - USE_AIKAR_FLAGS=true
            - MEMORY=12G
            - ENABLE_AUTOPAUSE=TRUE
            - MAX_TICK_TIME=-1

        volumes:
          - /etc/timezone:/etc/timezone:ro
          - ./data:/data

        restart: unless-stopped
        container_name: minecraft
        image: itzg/minecraft-server